#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



function __github_error()
{
    echo "$@" >&2
}

GITHUB_ERROR=__github_error


function __gitty::api::extract_headers()
{
    sed -n '1,/^\r*$/p' <<<"$1"
}

function __gitty::api::extract_body()
{
    sed '1,/^\r*$/d; $d' <<<"$1"
}

function __gitty::api::extract_http_code()
{
    sed -n '$p' <<<"$1"
}

# Make a generic HTTP request.
#
# @public
function gitty::api::request()
{
    local what="${1:-body}" expected="${2:-200}" ; shift 2

    function __gitty::api::request()
    {
        local accept user_agent basic_auth oauth_token
        local response headers body http_code
        local error_message

        # @cf https://developer.github.com/v3/media/#request-specific-version
        accept="-H 'Accept: application/vnd.github.v3+json'"

        # @cf https://developer.github.com/v3/#user-agent-required
        if [[ -n $GITTY_API_USER_AGENT ]]
        then
            user_agent="-H 'User-Agent: $GITTY_API_USER_AGENT'"
        fi

        if [[ -n $GITTY_API_BASIC_AUTH ]]
        then
            basic_auth="-u $GITTY_API_BASIC_AUTH"
        elif [[ -n $GITTY_API_OAUTH_TOKEN ]]
        then
            oauth_token="-H 'Authorization: token $GITTY_API_OAUTH_TOKEN'"
        fi

        # Perform HTTP request
        response="$(
            eval curl -is                                                  \
                "$accept"                                                  \
                "$user_agent"                                              \
                "$basic_auth"                                              \
                "$oauth_token"                                             \
                "$GITTY_API_CUSTOM_HEADERS"                 \
                --write-out '\\n%{http_code}\\n'                           \
                "$@"
        )"

        if [[ -n $GITTY_API_DEBUG ]]
        then
            echo "$response" >&2
        fi

        # Extract headers, body, HTTP code
          headers="$( __gitty::api::extract_headers   "$response")"
             body="$( __gitty::api::extract_body      "$response")"
        http_code="$( __gitty::api::extract_http_code "$response")"

        # Check HTTP code
        if [[ $http_code == 000 ]]
        then
            $GITHUB_ERROR "$GITTY_API_ERROR_HEADER [cURL error]"
            return $GITTY_API_ERROR
        elif [[ $what != http_code && $http_code != $expected ]]
        then
            error_message="$(jq -r .message <<<"$body")"
            $GITHUB_ERROR "$GITTY_API_ERROR_HEADER [$error_message]"
            return $GITTY_API_ERROR
        fi

        # Echo headers/body/http_code
        [[ $what == none ]] || eval echo "\"\$$what\""
    }

    __gitty::api::request "$@"
}

# Filter JSON content.
#
# @public
function gitty::api::filter()
{
    if [[ -n $GITTY_API_DO_NOT_PARSE_RESPONSE ]]
    then
        cat
    else
        jq -r "$@"
    fi
}

# Retrieve a resource.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::get()
{
    local url="$1" ; shift

    [[ -n $url ]] || return

    gitty::api::request body 200            \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | gitty::api::filter "$@"
}

# Extract a given value from the HTTP headers.
#
# @public
function gitty::api::extract_header_value()
{
    local headers="${1:?Headers needed}" key="${2:-[^:]\+}"

    echo "$headers" | sed -n "s/^$key: \(.*\)/\\1/p"
}

# Get the Link header values.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::extract_rels()
{
    local headers="${1:?Headers needed}" filter="${2:-.+}"
    local regex="<(.+)>\;[[:space:]]rel=\"($filter)\""

    IFS=, read -a rels <<<$(
        gitty::api::extract_header_value "$headers" Link
    )

    for rel in "${rels[@]}"
    do
        if [[ $rel =~ $regex ]]
        then
            printf "%s:%s\n" "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
        fi
    done
}

# Get the link relation for the given page of results.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::extract_rel()
{
    local headers="${1:?Headers needed}" key="${2:-next}"
    local regex="${key}:(.*)" rel

    rel="$(gitty::api::extract_rels "$headers" "$key")"
    if [[ $rel =~ $regex ]]
    then
        echo "${BASH_REMATCH[1]#${GITTY_API_ENDPOINT}}"
    fi
}

# Get the link relation for the next page of results.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::next()
{
    local headers="${1:?Headers needed}"
    gitty::api::extract_rel "$headers" next
}

# Get the link relation for the last page of results.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::last()
{
    local headers="${1:?Headers needed}"
    gitty::api::extract_rel "$headers" last
}

# Get the number of result pages.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::count()
{
    local headers="${1:?Headers needed}"
    local regex="page=([0-9]+)" last
    last="$(gitty::api::last "$headers")"
    [[ $last =~ $regex ]] && echo "${BASH_REMATCH[1]}"
}

# Get paginated items.
#
# @cf   https://developer.github.com/v3/#pagination
# @public
function gitty::api::paginate()
{
    local url="$1" key="$2"
    local limit="${3:-100}" callback="${4:-cat}"
    local count=0
    
    [[ -n $url || -n $key ]] || return

    while true
    do
        local response headers body
        local item next
        declare -a items

        response="$(
            gitty::api::request response 200        \
                "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
        )"

        headers="$( __gitty::api::extract_headers "$response")"
           body="$( __gitty::api::extract_body    "$response")"

        items=("$(echo "$body" | gitty::api::filter "if type == \"array\" then .[].\"$key\" else .items[].\"$key\" end")")

        for item in "${items[@]}"
        do
            (( count < limit )) || break 2
            ((count++))
            [[ -n $item ]] && echo "$item"
        done

        next="$(gitty::api::next "$headers")"
        [[ -z $next || $next == $url ]] && break
        url="$next"

    done | $callback
}

# Get the HTTP status code.
#
# @public
function gitty::api::status()
{
    local url="$1" ; shift

    [[ -n $url ]] || return

    gitty::api::request http_code 000       \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
}

# Get the HTTP headers.
#
# @public
function gitty::api::header()
{
    local url="$1" key="${2:-[^:]\+}"

    [[ -n $url ]] || return

    gitty::api::request headers 200         \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | grep "^$key: "
}

# Extract a given value from the HTTP headers.
#
# @public
function gitty::api::header_value()
{
    local url="$1" key="${2:-[^:]\+}"

    [[ -n $url ]] || return

    gitty::api::request headers 200         \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | sed -n "s/^$key: \(.*\)/\\1/p"
}

# Create a resource.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::post()
{
    local url="$1" data="$2" ; shift 2

    [[ -n $url || -n $GITTY_API_OAUTH_TOKEN ]] || return

    gitty::api::request body 201 -X POST    \
        "-H 'Content-Type: application/json'"                \
        --data "$(printf "%q" "$data")"                      \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | gitty::api::filter "$@"
}

# Specialized POST method that expects a 200 status code.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::post200()
{
    local url="$1" data="$2"
    local mime="${3:-application/json}"

    [[ -n $url ]] || return

    gitty::api::request body 200 -X POST           \
        "-H 'Content-Type: $mime'"                             \
        --data "$(printf "%q" "$data")"                        \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
}

# Create a resource in an asynchronous fashion.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::post202()
{
    local url="$1" data="$2" ; shift 2

    [[ -n $url || -n $GITTY_API_OAUTH_TOKEN ]] || return

    gitty::api::request body 202 -X POST    \
        "-H 'Content-Type: application/json'"                \
        --data "$(printf "%q" "$data")"                      \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | gitty::api::filter "$@"
}

# Update a resource with partial JSON data.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::patch()
{
    local url="$1" data="$2" ; shift 2

    [[ -n $url || -n $GITTY_API_OAUTH_TOKEN ]] || return

    gitty::api::request body 200 -X PATCH   \
        "-H 'Content-Type: application/json'"                \
        --data "$(printf "%q" "$data")"                      \
        "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")" \
        | gitty::api::filter "$@"
}

# Replace a resource or a collection.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::put()
{
    local url="$1" data="$2"

    [[ -n $url || -n $GITTY_API_OAUTH_TOKEN ]] || return

    if [[ -n $data ]]
    then
        gitty::api::request none 204 -X PUT \
            "-H 'Content-Type: application/json'"            \
            --data "$(printf "%q" "$data")"                  \
            "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
    else
        gitty::api::request none 204 -X PUT \
            -H "'Content-Length: 0'"                         \
            "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
    fi
}

# Delete a resouce.
#
# @cf   https://developer.github.com/v3/#http-verbs
# @public
function gitty::api::delete()
{
    local url="$1" data="$2"

    [[ -n $url || -n $GITTY_API_OAUTH_TOKEN ]] || return

    if [[ -n $data ]]
    then
        gitty::api::request none 204 -X DELETE  \
            "-H 'Content-Type: application/json'"                \
            --data "$(printf "%q" "$data")"                      \
            "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
    else
        gitty::api::request none 204 -X DELETE  \
            "$(printf "%q" "${GITTY_API_ENDPOINT}${url}")"
    fi
}

# Get API root endpoint.
#
# @cf   https://developer.github.com/v3/#root-endpoint
# @public
function gitty::api::endpoint()
{
    echo "$GITTY_API_ENDPOINT"
}

# Get API version.
#
# @cf   https://developer.github.com/v3/versions/#versions
# @public
function gitty::api::version()
{
    echo v3
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
