#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# List public events for a network of repositories
#
# @cf   https://developer.github.com/v3/activity/events/#list-public-events-for-a-network-of-repositories
# @public
function gitty::events::network()
{
    gitty::network::events "$@"
}

# List public organization events.
#
# @cf   https://developer.github.com/v3/activity/events/#list-public-organization-events
# @public
function gitty::events::org()
{
    gitty::org::events "$@"
}

# List public events IDs.
#
# @cf   https://developer.github.com/v3/activity/events/#list-public-events
# @public
function gitty::events::public()
{
    gitty::root::events "$@"
}

# List repository events IDs.
#
# @cf   https://developer.github.com/v3/activity/events/#list-repository-events
# @public
function gitty::events::repo()
{
    gitty::repo::events "$@"
}

# List organization events for the authenticated user.
# Note: This is the user's organization dashboard. You must be authenticated as
# the user to view this.
#
# @cf   https://developer.github.com/v3/activity/events/#list-organization-events-for-the-authenticated-user
# @public
function gitty::events::user_org_received_events()
{
    gitty::user::org_received_events "$@"
}

# List public events for a user.
#
# @cf   https://developer.github.com/v3/activity/events/#list-public-events-for-a-user
# @public
function gitty::events::user_public_received()
{
    gitty::user::public_received_events "$@"
}

# List events received by the authenticated user.
#
# @cf   https://developer.github.com/v3/activity/events/#list-events-received-by-the-authenticated-user
# @public
function gitty::events::user_received()
{
    gitty::user::received_events "$@"
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
