#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



# List all Codes of Conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#list-all-codes-of-conduct
# @public
function gitty::github::conducts()
{
    local url="/codes_of_conduct"

    (
        # The Codes of Conduct API is currently available for developers to
        # preview. To access the API during the preview period, we must provide
        # a custom media type in the Accept header.
        #
        # @cf https://developer.github.com/v3/codes_of_conduct/#codes-of-conduct

        GITTY_API_CUSTOM_HEADERS="$GITTY_API_CUSTOM_HEADERS -H 'Accept: application/vnd.github.scarlet-witch-preview+json'"
        gitty::api::get "$url" .[].key
    )
}

# List all the emojis available to use on GitHub.
#
# @cf   https://developer.github.com/v3/emojis/#emojis
# @public
function gitty::github::emojis()
{
    local url="/emojis"
    
    gitty::api::get "$url" keys[]
}

# List all .gitignore templates available to pass as an option when creating a
# repository.
#
# @cf   https://developer.github.com/v3/gitignore/#listing-available-templates
# @public
function gitty::github::gitignores()
{
    local url="/gitignore/templates"
    
    gitty::api::get "$url" .[]
}

# List all IP addresses (in CIDR format) specifying the Git servers for
# GitHub.com.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @public
function gitty::github::git_servers()
{
    local url="/meta"
    
    gitty::api::get "$url" .git[]
}

# Get a list of IP addresses in CIDR format specifying the addresses that
# incoming service hooks will originate from on GitHub.com.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @public
function gitty::github::hooks()
{
    local url="/meta"
    
    gitty::api::get "$url" .hooks[]
}

# Get a list of IP addresses in CIDR format specifying the addresses that
# source imports will originate from on GitHub.com.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @public
function gitty::github::importers()
{
    local url="/meta"
    
    gitty::api::get "$url" .importers[]
}

# List all licenses.
#
# @cf   https://developer.github.com/v3/licenses/#list-all-licenses
# @public
function gitty::github::licenses()
{
    local url="/licenses"
    
    gitty::api::get "$url" .[].key
}

# List all organizations.
#
# @cf   https://developer.github.com/v3/orgs/#list-all-organizations
# @public
function gitty::github::orgs()
{
    local since="${1:-0}" limit="${2:-100}" callback="${3:-cat}"
    local url="/organizations?since=$since"
    
    gitty::api::paginate "$url" login "$limit" "$callback"
}

# List all IP addresses (in CIDR format) specifying the A records for GitHub
# Pages.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @public
function gitty::github::pages()
{
    local url="/meta"
    
    gitty::api::get "$url" .pages[]
}

# Tell whether authentication with username and password is supported.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @public
function gitty::github::password_auth()
{
    local url="/meta" value
    
    gitty::api::get "$url" '.github_services_sha == true' > /dev/null
}

# List all public repositories.
#
# @cf   https://developer.github.com/v3/repos/#list-all-public-repositories
# @public
function gitty::github::repos()
{
    local since="${1:-0}" limit="${2:-100}" callback="${3:-cat}"
    local url="/repositories?since=$since"
    
    gitty::api::paginate "$url" full_name "$limit" "$callback"
}

# Get the currently-deployed SHA of github-services.
#
# @cf   https://developer.github.com/v3/meta/#meta
# @cf   https://github.com/github/github-services
# @public
function gitty::github::sha()
{
    local url="/meta"
    
    gitty::api::get "$url" .github_services_sha
}

# Get the GitHub global public timeline, in Atom format.
#
# @cf   https://developer.github.com/v3/activity/feeds/#list-feeds
# @public
function gitty::github::timeline()
{
    curl -s "$(gitty::github::timeline_url)"
}

# Get the GitHub global public timeline URI.
#
# @cf   https://developer.github.com/v3/activity/feeds/#list-feeds
# @public
function gitty::github::timeline_url()
{
    local url="/feeds"

    gitty::api::get "$url" .timeline_url
}

# List all users, in the order that they signed up on GitHub.
#
# @cf   https://developer.github.com/v3/users/#get-all-users
# @public
function gitty::github::users()
{
    local since="${1:-0}" limit="${2:-100}" callback="${3:-cat}"
    local url="/users?since=$since"
    
    gitty::api::paginate "$url" login "$limit" "$callback"
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
