#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



# Get all commonly used licenses.
#
# @cf   https://docs.github.com/en/rest/reference/licenses#get-all-commonly-used-licenses
# @public
function gitty::licenses::all()
{
    local url="/licenses"
    
    gitty::api::get "$url" .
}

# Get a license.
#
# @cf   https://docs.github.com/en/rest/reference/licenses#get-a-license
# @public
function gitty::licenses::license()
{
    local key="${1:-mit}"
    local url="/licenses/$key"
    
    gitty::api::get "$url" .
}

# Get the license for a repository.
#
# @cf   https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository
# @public
function gitty::licenses::repo()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/repos/$user/$repo/license"

    gitty::api::get "$url" .
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
