#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



# Get GitHub meta information.
#
# @cf   https://docs.github.com/en/rest/reference/meta#get-github-meta-information
# @public
function gitty::meta::all()
{
    local url="/meta"
    
    gitty::api::get "$url" .
}

# Get Octocat.
#
# @cf   https://docs.github.com/en/rest/reference/meta#get-octocat
# @public
function gitty::meta::octocat()
{
    local s="${1:-Gitty}"
    local url="/octocat?s=$s"
    local GITTY_API_DO_NOT_PARSE_RESPONSE=1
    
    gitty::api::get "$url" .
}

# GitHub API Root.
#
# @cf   https://docs.github.com/en/rest/reference/meta#github-api-root
# @public
function gitty::meta::root()
{
    local url="/"
    
    gitty::api::get "$url" .
}

# Get the Zen of GitHub
#
# @cf   https://docs.github.com/en/rest/reference/meta#get-the-zen-of-github
# @public
function gitty::meta::zen()
{
    local url="/zen"
    local GITTY_API_DO_NOT_PARSE_RESPONSE=1
    
    gitty::api::get "$url" .
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
