#!/bin/bash


################################################################################
#  ____ ____ ____ ____ ____ 
# ||G |||i |||t |||t |||y ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#                                        
# Gitty -- A GitHub client in Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



# Get repository by ID (undocumented).
#
# @cf   https://github.com/octokit/rest.js/issues/163
# @public
function gitty::repo::by_id()
{
    local id="${1:-40891491}" # bashlets
    local selector="${2:-full_name}"
    local url="/repositories/$id"

    gitty::api::get "$url" ".$selector"
}

# List commits on a repository.
#
# @cf   https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository
# @public
function gitty::repo::commits()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/repos/$user/$repo/commits"

    gitty::api::paginate "$url" sha "$limit" "$callback"
}

# List commit comments for a repository.
#
# @cf   https://developer.github.com/v3/repos/comments/#list-commit-comments-for-a-repository
# @public
function gitty::repo::comments()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/repos/$user/$repo/comments"

    gitty::api::paginate "$url" id "$limit" "$callback"
}

# Get a repository's code of conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#get-the-contents-of-a-repositorys-code-of-conduct
# @public
function gitty::repo::conduct()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/repos/$user/$repo/community/code_of_conduct"

    (
        # The Codes of Conduct API is currently available for developers to
        # preview. To access the API during the preview period, we must provide
        # a custom media type in the Accept header.
        #
        # @cf https://developer.github.com/v3/codes_of_conduct/#codes-of-conduct

        GITTY_API_CUSTOM_HEADERS="$GITTY_API_CUSTOM_HEADERS -H 'Accept: application/vnd.github.scarlet-witch-preview+json'"
        gitty::api::get "$url" .key
    )
}

# Create a new repository for the authenticated user.
#
# @cf   https://developer.github.com/v3/repos/#create
# @public
function gitty::repo::create()
{
    local repo="${1:?Repository name needed}"
    local url="/user/repos"
    local json

    json="{ \"name\": \"$repo\" }"
    gitty::api::post "$url" "$json" .name
}

# Delete a repository.
# Deleting a repository requires admin access. If OAuth is used, the
# `delete_repo` scope is required.
#
# @cf   https://developer.github.com/v3/repos/#delete-a-repository
# @public
function gitty::repo::delete()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/repos/$user/$repo"

    gitty::api::delete "$url"
}

# List repository events IDs.
#
# @cf   https://developer.github.com/v3/activity/events/#list-repository-events
# @public
function gitty::repo::events()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local selector="${3:-id}" callback="${4:-cat}"
    local url="/repos/$user/$repo/events"

    # Events support pagination, however the per_page option is unsupported.
    # The fixed page size is 30 items. Fetching up to ten pages is supported,
    # for a total of 300 events.
    gitty::api::paginate "$url" "$selector" 30 "$callback"
}

# Fork a repository.
# Note: Forking a Repository happens asynchronously. Therefore, we may have to
# wait a short period before accessing the new git objects. 
#
# @cf   https://developer.github.com/v3/repos/forks/#create-a-fork
# @public
function gitty::repo::fork()
{
    local user="${1:-octocat}"
    local repo="${2:-Spoon-Knife}"
    local org="$3"  # Optional parameter to specify the organization name if
                    # forking into an organization.

    local url="/repos/$user/$repo/forks"

    [[ -n $org ]] && url="$url&organization=$org"
    
    gitty::api::post202 "$url" "" .id
}

# List forks for a repository.
#
# @cf   https://developer.github.com/v3/repos/forks/#list-forks
# @public
function gitty::repo::forks()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local sort="${3:-newest}"  # newest, oldest, stargazers
    local limit="${4:-100}" callback="${5:-cat}"
    local url="/repos/$user/$repo/forks?sort=$sort"
    
    gitty::api::paginate "$url" id "$limit" "$callback"
}

# Check if a gist is starred.
#
# @cf   https://developer.github.com/v3/activity/starring/#check-if-you-are-starring-a-repository
# @public
function gitty::repo::is_starred()
{
    local owner="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/user/starred/$owner/$repo"
    local status

    status="$(gitty::api::status "$url")"

    [[ $status == 204 ]]
}

# List repository projects.
#
# @cf   https://developer.github.com/v3/projects/#list-repository-projects
# @public
function gitty::repo::projects()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local state="${3:-all}"  # open, closed, all
    local limit="${4:-100}" callback="${5:-cat}"
    local url="/repos/$user/$repo/projects?state=$state"
    
    (
        # The Projects API is currently available for developers to preview. To
        # access the API during the preview period, we must provide a custom
        # media type in the Accept header.
        #
        # @cf https://developer.github.com/v3/projects/

        GITTY_API_CUSTOM_HEADERS="$GITTY_API_CUSTOM_HEADERS -H 'Accept: application/vnd.github.inertia-preview+json'"
        gitty::api::paginate "$url" id "$limit" "$callback"
    )
}

# Return the preferred README for a repository.
#
# @cf   https://developer.github.com/v3/repos/contents/#get-the-readme
# @public
function gitty::repo::readme()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/repos/$user/$repo/readme"
    local download_url

    download_url="$(gitty::api::get "$url" | jq -r .download_url?)"
    [[ -n $download_url ]] && curl -s "$download_url"
}

# Star a repository.
#
# @cf   https://developer.github.com/v3/activity/starring/#star-a-repository
# @public
function gitty::repo::star()
{
    local owner="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/user/starred/$owner/$repo"

    gitty::api::put "$url"
}

# List Stargazers for a repository.
#
# @cf   https://developer.github.com/v3/activity/starring/#list-stargazers
# @public
function gitty::repo::stargazers()
{
    local owner="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/repos/$owner/$repo/stargazers"

    gitty::api::paginate "$url" login "$limit" "$callback"
}

# List tags for a repository.
#
# @cf   https://developer.github.com/v3/repos/#list-tags
# @public
function gitty::repo::tags()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/repos/$user/$repo/tags"
    
    gitty::api::paginate "$url" sha "$limit" "$callback"
}

# List all topics for a repository.
#
# @cf   https://developer.github.com/v3/repos/#list-all-topics-for-a-repository
# @public
function gitty::repo::topics()
{
    local user="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/repos/$user/$repo/topics"
    
    (
        # The topics property for repositories on GitHub is currently available
        # for developers to preview. To view the topics property in calls that
        # return repository results, we must provide a custom media type in the
        # Accept header.

        GITTY_API_CUSTOM_HEADERS="$GITTY_API_CUSTOM_HEADERS -H 'Accept: application/vnd.github.mercy-preview+json'"
        gitty::api::get "$url" .names[]
    )
}

# Unstar a repository.
#
# @cf   https://developer.github.com/v3/activity/starring/#unstar-a-repository
# @public
function gitty::repo::unstar()
{
    local owner="${1:?User name needed}"
    local repo="${2:?Repository name needed}"
    local url="/user/starred/$owner/$repo"

    gitty::api::delete "$url"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
