#!/bin/bash

# Downloads a random emoji

source ./gitty.sh
source ./gittybox

url="$(gitty::emojis::list | jq -r 'keys_unsorted[] as $k | "\(.[$k])"' | shuf | head -1)"
curl -s --output "$(basename "$url")" "$url"
